server:
  port: 8891
  forward-headers-strategy: native

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: be
  r2dbc:
    url: ${R2DBC_URL:r2dbc:postgresql://localhost:5432/personal}
    username: ${DB_USER:personal}
    password: ${DB_PASSWORD:personal}
  flyway:
    enabled: true
    url: ${FLYWAY_URL:jdbc:postgresql://localhost:5432/personal}
    user: ${FLYWAY_USER:personal}
    password: ${FLYWAY_PASSWORD:personal}
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.kotlinserversquad.com/realms/personalblog
          jwk-set-uri: https://keycloak.kotlinserversquad.com/realms/personalblog/protocol/openid-connect/certs
  cors:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${ENVIRONMENT:dev}

security:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3333,http://localhost:3335}

aws:
  ses:
    region: ${AWS_REGION:us-east-1}
    from-email: ${SES_FROM_EMAIL:noreply@jirihermann.com}
    from-name: ${SES_FROM_NAME:Blog Notification}
    enabled: ${SES_ENABLED:true}
    access-key-id: ${AWS_ACCESS_KEY_ID:}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY:}

email:
  admin-email: ${ADMIN_EMAIL:me@jirihermann.com}
  contact-subject: ${CONTACT_SUBJECT:New Contact Form Submission}

recaptcha:
  enabled: ${RECAPTCHA_ENABLED:true}
  secret: ${RECAPTCHA_SECRET:xxx}
  verify-url: https://www.google.com/recaptcha/api/siteverify
  minimum-score: ${RECAPTCHA_MINIMUM_SCORE:0.5}
  expected-action: ${RECAPTCHA_EXPECTED_ACTION:contact_form}
  expected-hostname: ${RECAPTCHA_EXPECTED_HOSTNAME:}
