apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: be
          image: ghcr.io/OWNER/REPO:main
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          env:
            - name: R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/personal
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: be-db
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-db
                  key: password
            - name: FLYWAY_URL
              value: jdbc:postgresql://postgres:5432/personal
            - name: FLYWAY_USER
              valueFrom:
                secretKeyRef:
                  name: be-db
                  key: user
            - name: FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: be-db
                  key: password
            - name: ALLOWED_ORIGINS
              value: http://localhost:3333
            - name: JWT_ISSUER_URI
              value: http://keycloak:8080/realms/personal

